# pylint: skip-file
# Generated by Django 4.2.11 on 2024-03-13 19:36

import sys

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit_external_sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='added',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='last_checked',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='removed',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        )
    ]

    if sys.version_info[0] > 2:
        operations.append(migrations.AlterField(
            model_name='sensordatapayload',
            name='definition',
            field=models.JSONField(),
        ))

        operations.append(migrations.AlterField(
            model_name='sensordatapayload',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ))
